import type { Tab } from '../App'
import { GarageIcon } from '../components/GarageIcons'
import type { GarageIconName } from '../components/GarageIcons'
const tools: {tab: Tab; icon: GarageIconName; title: string; detail: string}[] = [
  {tab: 'pickup', icon: 'pickup', title: 'Yellow Sack pickup', detail: 'Bag placement, truck access and your filling plan.'},
  {tab: 'people', icon: 'crew', title: 'The crew', detail: 'People and their assigned cleanup tasks.'},
  {tab: 'zones', icon: 'board', title: 'Task board', detail: 'Cleanup tasks organized by garage area.'},
  {tab: 'capture', icon: 'crate', title: 'Item list', detail: 'Loose items, owners, and decisions saved on this device.'},
  {tab: 'dashboard', icon: 'trophy', title: 'Task progress', detail: 'Team scores, completed tasks, and achievements.'},
  {tab: 'results', icon: 'trophy', title: 'Team standings', detail: 'Compare completed tasks and points for each person.'},
  {tab: 'sound', icon: 'sound', title: 'Sound controls', detail: 'Turn sound on or off and try each effect.'},
]
export function More({onNavigate}: {onNavigate: (tab: Tab) => void}) {
  return <main className="reset-home home-more"><header className="home-heading"><div><p className="home-eyebrow">GARAGE RESET</p><h1>Tools and help.</h1><p>Pickup planning, people, and instructions.</p></div></header><section className="home-more-tools" aria-label="More garage tools">{tools.map(tool => <button key={tool.tab} onClick={() => onNavigate(tool.tab)}><span className="home-tool-icon"><GarageIcon name={tool.icon}/></span><span><strong>{tool.title}</strong><small>{tool.detail}</small></span><span aria-hidden="true">→</span></button>)}</section><section className="home-guide" aria-labelledby="phone-guide"><p className="home-eyebrow">THE PHONE PLAYBOOK</p><h2 id="phone-guide">How to use this app.</h2><details open><summary>I want to clear a little space</summary><p>Tap <b>Missions</b>. Choose a patch, shelf, or crate and a 5, 10, or 15 minute round. Take a before photo, start the timer, and sort. Finish with an after photo and a clear parking path. You can pause and return to the same round.</p><button onClick={() => onNavigate('play')}>Choose a mission →</button></details><details><summary>I want to find out what’s in a crate</summary><p>Tap <b>Crates</b> and register or select a container. In <b>Locate</b>, add its shelf address and a photo. In <b>Open & sort</b>, type or dictate one item or group per line, then assign each a decision and destination. In <b>Repack</b>, record the new fill. This updates the volume goal.</p><button onClick={() => onNavigate('crates')}>Open Crates →</button></details><details><summary>I want to plan on my laptop</summary><p>Tap <b>Garage</b> for the 3D view, source photos, and object details. Use <b>Yellow Sack pickup</b> here in More for the bag plan. Crates and photo missions share between devices; pickup settings and garage footprint corrections currently stay on the device where you edit them.</p><button onClick={() => onNavigate('layout')}>Open the garage plan →</button></details><details><summary>How do the points work?</summary><p>A completed photo mission earns <b>100 XP</b>. Three completed rounds earn the next level. XP rewards a finished round; the 50% space goal comes separately from crate capacities and confirmed repacking. Cash rewards aren’t set up in the app yet.</p></details><details><summary>Where are my photos and changes?</summary><p>Use the same family link on phone and laptop. Wait for the saved or shared status before switching devices. A visible workspace refreshes about every 30 seconds. If you see a draft or conflict message, open Crates or Missions to review it and export a backup. Keep your original photos.</p></details></section></main>
}
